APIで例外が発生request.json
{"mail_address": "test@example.com", "api_area": {"password": "pass", "language": "JPN", "work_schedule_data": [{"company_code": "P420580863", "work_schedule_code": "0000000001", "work_schedule_name": "name2", "working_system_abbreviation": "na2", "is_job_before_start_time": 1, "job_start": "09:00", "job_end": "18:00", "term_from": "1998/10/02", "term_to": null, "default_work_schedule_flg": 2, "del_flag": false}]}}

stacktrace
Traceback (most recent call last):
  File "/var/www/jp/co/linkpoint/artemis/util/utility.py", line 397, in convert_datestr_2_date
    dt = datetime.datetime.strptime(datestr, '%Y/%m/%d')
TypeError: strptime() argument 1 must be str, not None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/jp/co/linkpoint/artemis/api_private/template/work_schedule/restful_api_private_update_work_schedule_template.py", line 265, in set_api_data
    workSchedulePrivate.term_to = self.utility.convert_datestr_2_date(term_to)
  File "/var/www/jp/co/linkpoint/artemis/util/utility.py", line 401, in convert_datestr_2_date
    raise ArtemisException(e)
TypeError: __init__() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/jp/co/linkpoint/artemis/api_private/template/template_api_private_artemis.py", line 356, in exec
    http_status = self.set_api_data()
  File "/var/www/jp/co/linkpoint/artemis/api_private/template/work_schedule/restful_api_private_update_work_schedule_template.py", line 290, in set_api_data
    raise ArtemisException(e)
TypeError: __init__() takes 1 positional argument but 2 were given

